config/routes.rb
Rails.application.routes.draw do
  root 'tweets#index'
  resources :tweets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :message, length: {maximum: 140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
      @tweet = Tweet.all
  end

  def new
      @tweet = Tweet.new
  end

  def create
      tweet = Tweet.new(message: params[:tweet][:message])
      tweet.save
      redirect_to tweets_path
  end

  def show
      @tweet = Tweet.find(params[:id])
  end

  def edit

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/index.html.erb
<h1>Twitter</h1>

<p><%= link_to 'つぶやく' , new_tweet_path %></p>
<% @tweet.each do|t|%>
  <p>
  <%= link_to t.message %>
  </p>
<% end %>


<p>編集</p>
<p>表示</p>
<p>削除</p>

app/views/tweets/new.html.erb
<h1>新規作成</h1>
<%=form_for @tweet, message:{action: :create}  do |t| %>
  <%=t.label :message, '新規投稿' %>
  <%=t.text_field :message %>

  <%=t.submit '投稿' %>
<% end %>

app/views/tweets/show.html.erb
<h1>Tweets#show</h1>
<p>Find me in app/views/tweets/show.html.erb</p>